let productsDB = [
  {
    id: 1,
    title: "laptop",
    size: "large",
    imageUrl: "images/1.jpg",
    qty: 1,
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    liked: false,
  },

  {
    id: 2,
    title: "laptop",
    size: "large",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "images/2.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 3,
    title: "laptop  ",
    size: "large",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "images/3.jpg",
    qty: 1,
    liked: false,
  },

  {
    id: 4,
    title: "laptop hp",
    size: "large",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/4.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 5,
    title: "laptop hp",
    size: "large",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/5.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 6,
    title: "laptop apple",
    size: "large",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/6.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 7,
    title: "apple",
    size: "small",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/7.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 8,
    title: "phone",
    size: "small",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/8.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 9,
    title: "samsung",
    size: "small",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/9.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 10,
    title: "oppo",
    size: "small",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/10.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 11,
    title: "oppo",
    size: "small",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/11.jpg",
    qty: 1,
    liked: false,
  },
  {
    id: 12,
    title: "samsung",
    size: "small",
    desc: "Lorem ipsum, dolor sit amet consectetur.",
    isMe: "N",
    imageUrl: "./images/12.jpg",
    qty: 1,
    liked: false,
  },
];

// localStorage.setItem("products", JSON.stringify(productsDB));
